### ISSUE TITLE
GerberCairoContext import error

### ISSUE THREAD

**Issue by noyart** [curtacircuitos/pcb-tools#98]
Hi! 
Im trying to set everyhing up and try the exampel code. Im new to python. 
I get this error when I run the exampel code. What can be the reason for the import error of the GerberCairoContext. Wrong version somewhere? I run a windows machine with python 3.

Exception has occurred: ImportError
cannot import name 'GerberCairoContext' from 'gerber.render' (C:\Users\Noy\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pcb_tools-0.1.6-py3.7.egg\gerber\render\_init_.py)
  File "G:\phytonscrips\AOI\gerbertest.py", line 2, in <module>
    from gerber.render import GerberCairoContext
  File "C:\Users\Noy\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Noy\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Users\Noy\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)

**Comment by hamiltonkibbe** [comment]
Think it needs to be imported from cairo_backend:

`from gerber.render.cairo_backend import GerberCairoContext`

**Comment by noyart** [comment]
Sorry for the late reply, I still get the same problem that it cant import on that line. 
I must have done something wrong during the installation right?

**Comment by phsilva** [comment]
Fixed on master, Thanks for the report.

**Comment by kahlju** [comment]
This is not fixed.  please open it back up.  @chintal ruined the master in his latest commit to overwrite all the changes in the commit where @phsilva fixed all of this.  I'm not sure how he/she ran GerberCairoContext with his code, but it does not work again.  I'm reinstalling it with the "correct" code version which is not the master file anymore.

**Comment by alvinsu51416** [comment]
Agreed with @kahlju, the new update does not fix the issue. I got the same error like @noyart did with pcb-tools 0.1.6

**Comment by senic35** [comment]
Is there a fix to this? The issue still persists and what hamiltonkibbe suggested doesn't work for me, I get the following error: `OSError: dlopen() failed to load a library: cairo / cairo-2 / cairo-gobject-2`

**Comment by vladiks** [comment]
I have the same problem as @noyart  `No module named 'gerber.render'; 'gerber' is not a package`

First line of example `import gerber` works, but running `print(dir(gerber))` shows only `['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'gerber']` , so there is for example no read method

**Comment by vladiks** [comment]
> I have the same problem as @noyart `No module named 'gerber.render'; 'gerber' is not a package`
> 
> First line of example `import gerber` works, but running `print(dir(gerber))` shows only `['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'gerber']` , so there is for example no read method

Ok, so I found out, that i named my python file gerber.py, so `import gerber` was actually importing my own file :-)

I renamed the file and used the import suggested by @hamiltonkibbe and it got me to "cannot load library 'libcairo.so.2'", so that is different issue

**Comment by wytr** [comment]
Bump, i just got the same Error which does not seem to be fixed by any advice given here.

**Comment by pablo-johnson** [comment]
For the ones using docker, I put this command in the Dockerfile and it solved the problem 
`RUN apt-get install -y libcairo2`

If you are not using docker, I supposed that it is solved just by running `apt-get install -y libcairo2` in the terminal.

**Comment by BrewingGeek** [comment]
'apt-get install -y libcairo2' my work for a Linux box but how about a Windows box...

ImportError: cannot import name 'GerberCairoContext' from 'gerber.render'
